/*******************************************************************************
* Header Files
*******************************************************************************/
#include "voice_assistant.h"
#include "profiler.h"
#include "app_events.h"
#ifdef USE_AUDIO_ENHANCEMENT
#include "audio_enhancement.h"
#endif
#include "pdm_mic.h"

/* Include the headers generated by the DEEPCRAFT Voice-Assistant cloud tool*/
#include MTB_WWD_NLU_APP_HEADER(PROJECT_PREFIX)
#include MTB_WWD_NLU_CONFIG_HEADER(PROJECT_PREFIX)

/*******************************************************************************
* Macros
*******************************************************************************/

/* This is the maximum size of the command string that can be detected by the 
 * voice assistant. 
 */
#define COMMAND_STRING_SIZE                     (250U) 

/* Number of audio channels sampled from microphones and processed */
#define NUM_AUDIO_CHANNELS                      (1U)

/* How often to print the MCPS (multiply by 10 ms) */
#define PRINT_MCPS_COUNT                        (100u)    

/* Uncomment to print MCPS (Voice-Assistant only) */
//#define SHOW_MCPS

/* Choose one of the following options to run the voice-assistant: 
 * VA_MODE_WW_SINGLE_CMD : For every wake word, a single command is detected
 * VA_MODE_WW_MULTI_CMD  : For every wake word, multiple commands can be detected
 * VA_MODE_WW_ONLY       : Only wake word detection is performed
 * VA_MODE_CMD_ONLY      : Only command detection is performed
 */
#define RUNNING_MODE            (VA_MODE_WW_SINGLE_CMD) 

/*****************************************************************************
 * Variables
 *****************************************************************************/

/* Required by the audio-voice-core to build */
uint8_t bf_coeffs[1];
uint32_t bf_coeffs_total_len;

int intent_value;
extern char *intent_text;
extern char *variable_text;
#ifdef SHOW_MCPS
/* Variables used to print and calculate MCPS */
uint32_t show_count = 0;
uint32_t cpu_cycle_sum = 0;
#endif

#ifdef SHOW_MCPS
/*******************************************************************************
 * Function Name: print_mcps
 *******************************************************************************
 * Summary:
 * Prints the number of CPU cycles in Mega cycles per second (MCPS)
 *  
 * Parameters:
 *  
 * Return:
 *  void
 *
 *******************************************************************************/
static void print_mcps(void)
{
    cpu_cycle_sum += profiler_get_cycles();
    show_count++;
    if(show_count >= PRINT_MCPS_COUNT) 
    {
        printf("Profiler: %u MCPS\r\n", cpu_cycle_sum/1000000);
        show_count = 0;
        cpu_cycle_sum = 0;
    }
}
#endif

/*******************************************************************************
 * Function Name: print_voice_assistant_status
 *******************************************************************************
 * Summary:
 * Prints an error message if wake-word detection result is not successful. 
 * Or a detection message if wake-word is detected.
 * Also update the Green LED to indicate the voice assistant state.
 *  
 * Parameters:
 *  result: result of the voice-assistant operation
 *  event: state of the voice-assistant operation
 *  va_data: data detected from the voice-assistant operation
 *
 * Return:
 *  void
 *
 *******************************************************************************/
static void print_voice_assistant_status(cy_rslt_t result, va_event_t event, va_data_t *va_data)
{
    char command_text[COMMAND_STRING_SIZE] = {0};

    if (result == VA_RSLT_LICENSE_ERROR)
    {
        printf("ERROR! Voice Assistant license expired!\r\n");
        handle_app_error();
    }
    else if ( result != VA_RSLT_SUCCESS )
    {
        printf("Error! voice_assistant_process!! Error code=%d\r\n", result);
    }
    else
    {
        if ( event == VA_EVENT_WW_DETECTED )
        {
            if (RUNNING_MODE != VA_MODE_WW_ONLY)
            {
                
            }
            printf("Wake-word detected!\r\n");
        }
        else if ( event == VA_EVENT_CMD_TIMEOUT )
        {
            if (RUNNING_MODE != VA_MODE_CMD_ONLY)
            {
                
                printf("Command Timeout!\r\n");
            }
        }
        else if ( event == VA_EVENT_CMD_SILENCE_TIMEOUT )
        {
            if ((RUNNING_MODE != VA_MODE_WW_MULTI_CMD) && (RUNNING_MODE != VA_MODE_CMD_ONLY))
            {
                
                printf("Pre Silence Timeout!\r\n");
            }
        }
        else if ( event == VA_EVENT_CMD_DETECTED )
        {
            if (RUNNING_MODE == VA_MODE_WW_SINGLE_CMD)
            {
                
            }
            printf("Command detected: ");
            if (CY_RSLT_SUCCESS == voice_assistant_get_command(command_text))
            {
                printf("%s\r\n\r\n", command_text);
            }

            if (va_data == NULL)
            {
                return;
            }

            intent_value = 0;
            intent_text = NULL;
            variable_text = NULL;
            printf("Intent name: %s\r\n", MTB_NLU_INTENT_NAME_LIST(PROJECT_PREFIX)[va_data->intent_index] );

            if (va_data->num_var != 0)
            {
                printf("Variable values: ");
                for (int i = 0; i < va_data->num_var; i++)
                {
                    if (va_data->variable[i].unit_idx < 0)
                    {
                        printf("%s ", MTB_NLU_VARIABLE_PHRASE_LIST(PROJECT_PREFIX)[va_data->variable[i].value]);
                    }
                    else
                    {
                        printf("%d ", va_data->variable[i].value);
                    }
                }
                printf("\n\rVariable units : ");
                for (int i = 0; i < va_data->num_var; i++)
                {
                    if (va_data->variable[i].unit_idx < 0)
                    {
                        printf("---");
                    }
                    else
                    {
                        printf("%s", MTB_NLU_UNIT_PHRASE_LIST(PROJECT_PREFIX)[va_data->variable[i].unit_idx]);
                    }
                }
                printf("\n\r");
            }
            printf("\n\r");
            intent_text = (char *)MTB_NLU_INTENT_NAME_LIST(PROJECT_PREFIX)[va_data->intent_index];
            variable_text = (char *)MTB_NLU_VARIABLE_PHRASE_LIST(PROJECT_PREFIX)[va_data->variable[0].value];
            handle_command_for_ui = true;
        }
    }
}

/*******************************************************************************
 * Function Name: run_voice_assistant_process
 *******************************************************************************
 * Summary:
 * Run the voice assistant process and print any information in the terminal.
 *  
 * Parameters:
 *  audio_frame: pointer to the audio data frame
 *
 * Return:
 *  void
 *
 *******************************************************************************/
static void run_voice_assistant_process(int16_t *audio_frame)
{
    va_rslt_t va_result;
    va_data_t va_data;
    va_event_t va_event;

#ifdef SHOW_MCPS
    profiler_start();
#endif    
    /* Process the audio data */
    va_result = voice_assistant_process(audio_frame, &va_event, &va_data);
#ifdef SHOW_MCPS
    profiler_stop();
    print_mcps();
#endif

    /* Print the status of the voice assistant */
    print_voice_assistant_status(va_result, va_event, &va_data);

    if (va_event == VA_EVENT_CMD_DETECTED)
    {
         //slider_change(va_data.intent_index,va_data.variable[0].value);
    }

}

/*******************************************************************************
 * Function Name: voice_assistant_task
 *******************************************************************************
 * Summary:
 * This is the FreeRTOS task to execute the DEEPCRAFT voice assistant routines.
 *
 * Parameters:
 *  void * arg
 *
 * Return:
 *  void
 *
 *******************************************************************************/
void voice_assistant_task(void * arg)
{
    int16_t *audio_frame;
    va_rslt_t va_result;
    
    /* Initialize the PDM microphone */
    pdm_mic_init();

    // Initialize the profiler to print MCPS
    #ifdef SHOW_MCPS
        profiler_init();
    #endif /* SHOW_MCPS */   

    /* If AFE is used, intialize the audio enhancement */
    #ifdef USE_AUDIO_ENHANCEMENT
        ae_rslt_t ae_result;

        ae_result = audio_enhancement_init(NUM_AUDIO_CHANNELS);
        if (ae_result != AE_RSLT_SUCCESS)
        {
            printf("Error initializing the audio enhancement. Error code=%d\r\n", ae_result);
            handle_app_error();
        }
        else
        {
            printf("Audio Enhancement initialized!\r\n");
        }
    #endif /* USE_AUDIO_ENHANCEMENT */
    /* Initialize the voice assistant */
    va_result = voice_assistant_init(RUNNING_MODE);

    if (va_result != VA_RSLT_SUCCESS)
    {
        printf("Error initializing the voice assistant. Error code=%d\r\n", va_result);
        handle_app_error();
    }
    else
    {
        printf("Voice Assistant initialized!\r\n\r\n");
    }

    /* Print the instructions */
    if ((RUNNING_MODE == VA_MODE_WW_SINGLE_CMD) || (RUNNING_MODE == VA_MODE_WW_MULTI_CMD)) 
    {
        printf("\n\rSay the wake-word \"%s\" followed by a command.\n\r\n\r", 
               MTB_WWD_NLU_CONFIG_WAKE_WORD_STR(PROJECT_PREFIX)[0]);
    } 
    else if (RUNNING_MODE == VA_MODE_WW_ONLY)
    {
        printf("\n\rSay the wake-word \"%s\".\n\r\n\r", 
               MTB_WWD_NLU_CONFIG_WAKE_WORD_STR(PROJECT_PREFIX)[0]);
    } 
    else if (RUNNING_MODE == VA_MODE_CMD_ONLY)
    {
        printf("\n\rSay a command.\n\r");
    }

    printf("\n\r");

    for (;;)
    {
        /* Get audio data */
        pdm_mic_get_data(&audio_frame);

   
#ifdef USE_AUDIO_ENHANCEMENT
        /* Apply the audio enhancement if AFE is enabled */
        ae_result = audio_enhancement_feed_input(audio_frame, NULL);
        if (ae_result == AE_RSLT_LICENSE_ERROR)
        {
            printf("ERROR! Audio Enhancement license expired!\r\n");
            handle_app_error();
        }
#else   

        /* If Audio Enhancement is not used, run voice-assistant 
         * directly with the microphone data */
        run_voice_assistant_process(audio_frame);

#endif  /* USE_AUDIO_ENHANCEMENT */       

    }  
}

#ifdef USE_AUDIO_ENHANCEMENT
/*******************************************************************************
 * Function Name: audio_enhancement_process_output
 *******************************************************************************
 * Summary:
 * Strong implementation to process the audio enhancement output.
 *
 * Parameters:
 *  output_buffer: pointer to the output audio data buffer.
 *
 * Return:
 *  void
 *
 *******************************************************************************/
void audio_enhancement_process_output(ae_buffer_info_t *output_buffer)
{
    /* Use the output data from the audio enhancement with the voice-assistant */
    run_voice_assistant_process(output_buffer->output_buf);
}
#endif

/* [] END OF FILE */