// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Hackathon_squareline

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void temp_change(lv_event_t * e);
void play_music(lv_event_t * e);
void pause_music(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
