// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: hui

#include "../ui.h"

void ui_comp_backbutton_create_hook(lv_obj_t * comp)
{
}
