// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: hui

#include "../ui.h"

void ui_event_comp_backbutton_backbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_backbutton = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FloorScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_FloorScreen_screen_init);
    }
}

// COMPONENT backbutton

lv_obj_t * ui_backbutton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_backbutton;
    cui_backbutton = lv_image_create(comp_parent);
    lv_image_set_src(cui_backbutton, &ui_img_icn_back_png);
    lv_obj_set_width(cui_backbutton, LV_SIZE_CONTENT);   /// 19
    lv_obj_set_height(cui_backbutton, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(cui_backbutton, -353);
    lv_obj_set_y(cui_backbutton, -182);
    lv_obj_set_align(cui_backbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_backbutton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_backbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(cui_backbutton, 400);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BACKBUTTON_NUM);
    children[UI_COMP_BACKBUTTON_BACKBUTTON] = cui_backbutton;
    lv_obj_add_event_cb(cui_backbutton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_backbutton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_backbutton, ui_event_comp_backbutton_backbutton, LV_EVENT_ALL, children);
    ui_comp_backbutton_create_hook(cui_backbutton);
    return cui_backbutton;
}

