// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: hui

#ifndef _UI_COMP_BACKBUTTON_H
#define _UI_COMP_BACKBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT backbutton
#define UI_COMP_BACKBUTTON_BACKBUTTON 0
#define _UI_COMP_BACKBUTTON_NUM 1
lv_obj_t * ui_backbutton_create(lv_obj_t * comp_parent);
void ui_event_comp_backbutton_backbutton(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
