// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Hackathon_squareline

#ifndef UI_SENSORS_H
#define UI_SENSORS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Sensors
extern void ui_Sensors_screen_init(void);
extern void ui_Sensors_screen_destroy(void);
extern lv_obj_t * ui_Sensors;
extern lv_obj_t * ui_sensorslabel;
extern void ui_event_homebtn1(lv_event_t * e);
extern lv_obj_t * ui_homebtn1;
extern lv_obj_t * ui_home2;
extern void ui_event_rightbtns(lv_event_t * e);
extern lv_obj_t * ui_rightbtns;
extern void ui_event_leftbtns(lv_event_t * e);
extern lv_obj_t * ui_leftbtns;
extern void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

