// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Hackathon_squareline

#include "../ui.h"

lv_obj_t * ui_Sensors = NULL;
lv_obj_t * ui_sensorslabel = NULL;
lv_obj_t * ui_homebtn1 = NULL;
lv_obj_t * ui_home2 = NULL;
lv_obj_t * ui_rightbtns = NULL;
lv_obj_t * ui_leftbtns = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
// event funtions
void ui_event_homebtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Info, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_Info_screen_init);
    }
}

void ui_event_rightbtns(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Graphics, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Graphics_screen_init);
    }
}

void ui_event_leftbtns(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Audio, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Audio_screen_init);
    }
}

void ui_event_Arc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        temp_change(e);
    }
}

// build funtions
void temp_change(lv_event_t * e)
{
    lv_obj_t * arc = lv_event_get_target_obj(e);
    uint8_t value = lv_arc_get_value(arc);

    lv_label_set_text_fmt(ui_Label6,"%d°C",value);
}

void ui_Sensors_screen_init(void)
{
    ui_Sensors = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Sensors, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Sensors, lv_color_hex(0x9DACC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Sensors, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sensorslabel = lv_label_create(ui_Sensors);
    lv_obj_set_width(ui_sensorslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sensorslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sensorslabel, -4);
    lv_obj_set_y(ui_sensorslabel, -194);
    lv_obj_set_align(ui_sensorslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sensorslabel, "SENSING");
    lv_obj_set_style_text_color(ui_sensorslabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sensorslabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_sensorslabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sensorslabel, &ui_font_SS52, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homebtn1 = lv_button_create(ui_Sensors);
    lv_obj_set_width(ui_homebtn1, 67);
    lv_obj_set_height(ui_homebtn1, 66);
    lv_obj_set_x(ui_homebtn1, 326);
    lv_obj_set_y(ui_homebtn1, -189);
    lv_obj_set_align(ui_homebtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homebtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homebtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homebtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_homebtn1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_homebtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home2 = lv_image_create(ui_homebtn1);
    lv_image_set_src(ui_home2, &ui_img_icn_home_png);
    lv_obj_set_width(ui_home2, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_home2, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_home2, -4);
    lv_obj_set_y(ui_home2, -10);
    lv_obj_set_align(ui_home2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_home2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rightbtns = lv_image_create(ui_Sensors);
    lv_image_set_src(ui_rightbtns, &ui_img_icn_back1_png);
    lv_obj_set_width(ui_rightbtns, 82);
    lv_obj_set_height(ui_rightbtns, 70);
    lv_obj_set_x(ui_rightbtns, 324);
    lv_obj_set_y(ui_rightbtns, -14);
    lv_obj_set_align(ui_rightbtns, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rightbtns, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_rightbtns, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leftbtns = lv_image_create(ui_Sensors);
    lv_image_set_src(ui_leftbtns, &ui_img_icn_back_png);
    lv_obj_set_width(ui_leftbtns, 82);
    lv_obj_set_height(ui_leftbtns, 70);
    lv_obj_set_x(ui_leftbtns, -358);
    lv_obj_set_y(ui_leftbtns, -12);
    lv_obj_set_align(ui_leftbtns, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftbtns, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_leftbtns, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_Sensors);
    lv_obj_set_width(ui_Arc1, 328);
    lv_obj_set_height(ui_Arc1, 253);
    lv_obj_set_x(ui_Arc1, -83);
    lv_obj_set_y(ui_Arc1, 2);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc1, 12, 50);
    lv_arc_set_value(ui_Arc1, 34);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x15183B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Sensors);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -124);
    lv_obj_set_y(ui_Label6, 2);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "34°C");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_SS52, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Sensors);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -122);
    lv_obj_set_y(ui_Label8, 135);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Temperature");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Sensors);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 150);
    lv_obj_set_y(ui_Label13, -41);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "CO2 : 450 ppm");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Sensors);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 135);
    lv_obj_set_y(ui_Label14, 15);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "IAQ : GOOD");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_homebtn1, ui_event_homebtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rightbtns, ui_event_rightbtns, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_leftbtns, ui_event_leftbtns, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc1, ui_event_Arc1, LV_EVENT_ALL, NULL);

}

void ui_Sensors_screen_destroy(void)
{
    if(ui_Sensors) lv_obj_del(ui_Sensors);

    // NULL screen variables
    ui_Sensors = NULL;
    ui_sensorslabel = NULL;
    ui_homebtn1 = NULL;
    ui_home2 = NULL;
    ui_rightbtns = NULL;
    ui_leftbtns = NULL;
    ui_Arc1 = NULL;
    ui_Label6 = NULL;
    ui_Label8 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;

}
