// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Hackathon_squareline

#include "../ui.h"

lv_obj_t * ui_Voice = NULL;
lv_obj_t * ui_voicelabel = NULL;
lv_obj_t * ui_homebtn2 = NULL;
lv_obj_t * ui_home1 = NULL;
lv_obj_t * ui_rightbtnv = NULL;
lv_obj_t * ui_leftbtnv = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_mic = NULL;
// event funtions
void ui_event_homebtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Info, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_Info_screen_init);
    }
}

void ui_event_rightbtnv(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Audio, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Audio_screen_init);
    }
}

void ui_event_leftbtnv(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Graphics, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Graphics_screen_init);
    }
}

// build funtions

void ui_Voice_screen_init(void)
{
    ui_Voice = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Voice, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Voice, lv_color_hex(0x9DACC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Voice, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voicelabel = lv_label_create(ui_Voice);
    lv_obj_set_width(ui_voicelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voicelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voicelabel, -21);
    lv_obj_set_y(ui_voicelabel, -197);
    lv_obj_set_align(ui_voicelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voicelabel, "VOICE");
    lv_obj_set_style_text_color(ui_voicelabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_voicelabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_voicelabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voicelabel, &ui_font_SS48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homebtn2 = lv_button_create(ui_Voice);
    lv_obj_set_width(ui_homebtn2, 67);
    lv_obj_set_height(ui_homebtn2, 66);
    lv_obj_set_x(ui_homebtn2, 326);
    lv_obj_set_y(ui_homebtn2, -189);
    lv_obj_set_align(ui_homebtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homebtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homebtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homebtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_homebtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_homebtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home1 = lv_image_create(ui_homebtn2);
    lv_image_set_src(ui_home1, &ui_img_icn_home_png);
    lv_obj_set_width(ui_home1, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_home1, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_home1, -4);
    lv_obj_set_y(ui_home1, -10);
    lv_obj_set_align(ui_home1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_home1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rightbtnv = lv_image_create(ui_Voice);
    lv_image_set_src(ui_rightbtnv, &ui_img_icn_back1_png);
    lv_obj_set_width(ui_rightbtnv, 82);
    lv_obj_set_height(ui_rightbtnv, 70);
    lv_obj_set_x(ui_rightbtnv, 324);
    lv_obj_set_y(ui_rightbtnv, -14);
    lv_obj_set_align(ui_rightbtnv, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rightbtnv, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_rightbtnv, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leftbtnv = lv_image_create(ui_Voice);
    lv_image_set_src(ui_leftbtnv, &ui_img_icn_back_png);
    lv_obj_set_width(ui_leftbtnv, 82);
    lv_obj_set_height(ui_leftbtnv, 70);
    lv_obj_set_x(ui_leftbtnv, -358);
    lv_obj_set_y(ui_leftbtnv, -12);
    lv_obj_set_align(ui_leftbtnv, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftbtnv, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_leftbtnv, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Voice);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 99);
    lv_obj_set_y(ui_Label3, -46);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3,
                      "Hey Infineon, Switch/Change to\n                      GREEN\n                        BLUE\n                         RED");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Voice);
    lv_slider_set_value(ui_Slider1, 65, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 147);
    lv_obj_set_height(ui_Slider1, 359);
    lv_obj_set_x(ui_Slider1, -193);
    lv_obj_set_y(ui_Slider1, 14);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x15183B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Label7 = lv_label_create(ui_Voice);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 89);
    lv_obj_set_y(ui_Label7, 89);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7,
                      "Hey Infineon, Set Slider \n                    MIN\n                    MAX\n                   ZERO");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mic = lv_image_create(ui_Voice);
    lv_image_set_src(ui_mic, &ui_img_mic_png);
    lv_obj_set_width(ui_mic, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_mic, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_mic, -13);
    lv_obj_set_y(ui_mic, 193);
    lv_obj_set_align(ui_mic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mic, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_mic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_homebtn2, ui_event_homebtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rightbtnv, ui_event_rightbtnv, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_leftbtnv, ui_event_leftbtnv, LV_EVENT_ALL, NULL);

}

void ui_Voice_screen_destroy(void)
{
    if(ui_Voice) lv_obj_del(ui_Voice);

    // NULL screen variables
    ui_Voice = NULL;
    ui_voicelabel = NULL;
    ui_homebtn2 = NULL;
    ui_home1 = NULL;
    ui_rightbtnv = NULL;
    ui_leftbtnv = NULL;
    ui_Label3 = NULL;
    ui_Slider1 = NULL;
    ui_Label7 = NULL;
    ui_mic = NULL;

}
