// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Hackathon_squareline

#ifndef UI_AUDIO_H
#define UI_AUDIO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Audio
extern void ui_Audio_screen_init(void);
extern void ui_Audio_screen_destroy(void);
extern lv_obj_t * ui_Audio;
extern lv_obj_t * ui_audiolabel;
extern void ui_event_homebtn3(lv_event_t * e);
extern lv_obj_t * ui_homebtn3;
extern lv_obj_t * ui_home3;
extern void ui_event_rightbtna(lv_event_t * e);
extern lv_obj_t * ui_rightbtna;
extern void ui_event_leftbtna(lv_event_t * e);
extern lv_obj_t * ui_leftbtna;
extern lv_obj_t * ui_sound;
extern lv_obj_t * ui_music;
extern void ui_event_play(lv_event_t * e);
extern lv_obj_t * ui_play;
extern void ui_event_pause(lv_event_t * e);
extern lv_obj_t * ui_pause;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

