// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Hackathon_squareline

#include "../ui.h"

lv_obj_t * ui_Audio = NULL;
lv_obj_t * ui_audiolabel = NULL;
lv_obj_t * ui_homebtn3 = NULL;
lv_obj_t * ui_home3 = NULL;
lv_obj_t * ui_rightbtna = NULL;
lv_obj_t * ui_leftbtna = NULL;
lv_obj_t * ui_sound = NULL;
lv_obj_t * ui_music = NULL;
lv_obj_t * ui_play = NULL;
lv_obj_t * ui_pause = NULL;
// event funtions
void ui_event_homebtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Info, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_Info_screen_init);
    }
}

void ui_event_rightbtna(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Sensors, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Sensors_screen_init);
    }
}

void ui_event_leftbtna(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Voice, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Voice_screen_init);
    }
}

void ui_event_play(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_pause, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_play, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        play_music(e);
    }
}

void ui_event_pause(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_pause, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_play, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        pause_music(e);
    }
}

// build funtions

void ui_Audio_screen_init(void)
{
    ui_Audio = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Audio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Audio, lv_color_hex(0x9DACC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Audio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_audiolabel = lv_label_create(ui_Audio);
    lv_obj_set_width(ui_audiolabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_audiolabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_audiolabel, 0);
    lv_obj_set_y(ui_audiolabel, -195);
    lv_obj_set_align(ui_audiolabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_audiolabel, "AUDIO");
    lv_obj_set_style_text_color(ui_audiolabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_audiolabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_audiolabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_audiolabel, &ui_font_SS52, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homebtn3 = lv_button_create(ui_Audio);
    lv_obj_set_width(ui_homebtn3, 67);
    lv_obj_set_height(ui_homebtn3, 66);
    lv_obj_set_x(ui_homebtn3, 326);
    lv_obj_set_y(ui_homebtn3, -189);
    lv_obj_set_align(ui_homebtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homebtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homebtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homebtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_homebtn3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_homebtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home3 = lv_image_create(ui_homebtn3);
    lv_image_set_src(ui_home3, &ui_img_icn_home_png);
    lv_obj_set_width(ui_home3, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_home3, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_home3, -4);
    lv_obj_set_y(ui_home3, -10);
    lv_obj_set_align(ui_home3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_home3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rightbtna = lv_image_create(ui_Audio);
    lv_image_set_src(ui_rightbtna, &ui_img_icn_back1_png);
    lv_obj_set_width(ui_rightbtna, 82);
    lv_obj_set_height(ui_rightbtna, 70);
    lv_obj_set_x(ui_rightbtna, 324);
    lv_obj_set_y(ui_rightbtna, -14);
    lv_obj_set_align(ui_rightbtna, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rightbtna, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_rightbtna, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leftbtna = lv_image_create(ui_Audio);
    lv_image_set_src(ui_leftbtna, &ui_img_icn_back_png);
    lv_obj_set_width(ui_leftbtna, 82);
    lv_obj_set_height(ui_leftbtna, 70);
    lv_obj_set_x(ui_leftbtna, -358);
    lv_obj_set_y(ui_leftbtna, -12);
    lv_obj_set_align(ui_leftbtna, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftbtna, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_leftbtna, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sound = lv_image_create(ui_Audio);
    lv_image_set_src(ui_sound, &ui_img_soundd_png);
    lv_obj_set_width(ui_sound, LV_SIZE_CONTENT);   /// 250
    lv_obj_set_height(ui_sound, LV_SIZE_CONTENT);    /// 250
    lv_obj_set_x(ui_sound, 15);
    lv_obj_set_y(ui_sound, -18);
    lv_obj_set_align(ui_sound, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sound, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_sound, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_music = lv_image_create(ui_Audio);
    lv_image_set_src(ui_music, &ui_img_music_png);
    lv_obj_set_width(ui_music, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_music, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_music, -7);
    lv_obj_set_y(ui_music, 144);
    lv_obj_set_align(ui_music, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_music, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_music, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_play = lv_image_create(ui_Audio);
    lv_image_set_src(ui_play, &ui_img_play_png);
    lv_obj_set_width(ui_play, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(ui_play, LV_SIZE_CONTENT);    /// 60
    lv_obj_set_x(ui_play, -172);
    lv_obj_set_y(ui_play, -16);
    lv_obj_set_align(ui_play, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_play, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_play, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pause = lv_image_create(ui_Audio);
    lv_image_set_src(ui_pause, &ui_img_ppause_png);
    lv_obj_set_width(ui_pause, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_pause, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_pause, -178);
    lv_obj_set_y(ui_pause, -16);
    lv_obj_set_align(ui_pause, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pause, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_pause, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_homebtn3, ui_event_homebtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rightbtna, ui_event_rightbtna, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_leftbtna, ui_event_leftbtna, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_play, ui_event_play, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pause, ui_event_pause, LV_EVENT_ALL, NULL);

}

void ui_Audio_screen_destroy(void)
{
    if(ui_Audio) lv_obj_del(ui_Audio);

    // NULL screen variables
    ui_Audio = NULL;
    ui_audiolabel = NULL;
    ui_homebtn3 = NULL;
    ui_home3 = NULL;
    ui_rightbtna = NULL;
    ui_leftbtna = NULL;
    ui_sound = NULL;
    ui_music = NULL;
    ui_play = NULL;
    ui_pause = NULL;

}
