// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: Hackathon_squareline

#ifndef UI_GRAPHICS_H
#define UI_GRAPHICS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Graphics
extern void ui_Graphics_screen_init(void);
extern void ui_Graphics_screen_destroy(void);
extern lv_obj_t * ui_Graphics;
extern lv_obj_t * ui_graphicslabel;
extern void ui_event_homebtn(lv_event_t * e);
extern lv_obj_t * ui_homebtn;
extern lv_obj_t * ui_home;
extern void ui_event_rightbtng(lv_event_t * e);
extern lv_obj_t * ui_rightbtng;
extern void ui_event_leftbtng(lv_event_t * e);
extern lv_obj_t * ui_leftbtng;
extern void ui_event_Start(lv_event_t * e);
extern lv_obj_t * ui_Start;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_gamepanel;
extern lv_obj_t * ui_Easy;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Hard;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Medium;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Gametitle;
extern void ui_event_exitgame(lv_event_t * e);
extern lv_obj_t * ui_exitgame;
extern lv_obj_t * ui_arrowimg2;
extern lv_obj_t * ui_Score;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

