// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: Hackathon_squareline

#include "../ui.h"
#include <stdio.h>
#include <stdlib.h>

lv_obj_t * ui_Graphics;
lv_obj_t * ui_graphicslabel;
lv_obj_t * ui_homebtn;
lv_obj_t * ui_home;
lv_obj_t * ui_rightbtng;
lv_obj_t * ui_leftbtng;
lv_obj_t * ui_Start;
lv_obj_t * ui_Label2;
lv_obj_t * ui_gamepanel;
lv_obj_t * ui_Easy;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Hard;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Medium;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Gametitle;
lv_obj_t * ui_exitgame;
lv_obj_t * ui_arrowimg2;
lv_obj_t * ui_Score;

static lv_obj_t *bucket;
static int score = 0;
static int ball_speed = 2000;
static lv_timer_t *ball_timer = NULL;

static void difficulty_cb(lv_event_t * e);
static void spawn_ball(lv_timer_t * timer);
static void ball_anim_cb(void * var, int32_t y);
static void bucket_move_cb(lv_event_t * e);

// event funtions
void ui_event_homebtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Info, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_Info_screen_init);
    }
}

void ui_event_rightbtng(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Voice, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Voice_screen_init);
    }
}

void ui_event_leftbtng(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Sensors, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Sensors_screen_init);
    }
}

void ui_event_Start(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_gamepanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_leftbtng, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_rightbtng, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_exitgame(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_gamepanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_leftbtng, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_rightbtng, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// build funtions

void ui_Graphics_screen_init(void)
{
    ui_Graphics = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Graphics, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Graphics, lv_color_hex(0x9DACC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Graphics, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphicslabel = lv_label_create(ui_Graphics);
    lv_obj_set_width(ui_graphicslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphicslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphicslabel, -12);
    lv_obj_set_y(ui_graphicslabel, -196);
    lv_obj_set_align(ui_graphicslabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphicslabel, "GRAPHICS");
    lv_obj_set_style_text_color(ui_graphicslabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphicslabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_graphicslabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphicslabel, &ui_font_SS52, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homebtn = lv_button_create(ui_Graphics);
    lv_obj_set_width(ui_homebtn, 67);
    lv_obj_set_height(ui_homebtn, 66);
    lv_obj_set_x(ui_homebtn, 326);
    lv_obj_set_y(ui_homebtn, -189);
    lv_obj_set_align(ui_homebtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_homebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_homebtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_homebtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homebtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_homebtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_homebtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home = lv_image_create(ui_homebtn);
    lv_image_set_src(ui_home, &ui_img_icn_home_png);
    lv_obj_set_width(ui_home, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_home, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_home, -4);
    lv_obj_set_y(ui_home, -10);
    lv_obj_set_align(ui_home, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rightbtng = lv_image_create(ui_Graphics);
    lv_image_set_src(ui_rightbtng, &ui_img_icn_back1_png);
    lv_obj_set_width(ui_rightbtng, 82);
    lv_obj_set_height(ui_rightbtng, 70);
    lv_obj_set_x(ui_rightbtng, 324);
    lv_obj_set_y(ui_rightbtng, -14);
    lv_obj_set_align(ui_rightbtng, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rightbtng, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_rightbtng, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_leftbtng = lv_image_create(ui_Graphics);
    lv_image_set_src(ui_leftbtng, &ui_img_icn_back_png);
    lv_obj_set_width(ui_leftbtng, 82);
    lv_obj_set_height(ui_leftbtng, 70);
    lv_obj_set_x(ui_leftbtng, -358);
    lv_obj_set_y(ui_leftbtng, -12);
    lv_obj_set_align(ui_leftbtng, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftbtng, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_leftbtng, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Start = lv_button_create(ui_Graphics);
    lv_obj_set_width(ui_Start, 294);
    lv_obj_set_height(ui_Start, 117);
    lv_obj_set_x(ui_Start, -6);
    lv_obj_set_y(ui_Start, -6);
    lv_obj_set_align(ui_Start, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Start, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Start, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Start, lv_color_hex(0x15183B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Start);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "START GAME");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gamepanel = lv_obj_create(ui_Graphics);
    lv_obj_set_width(ui_gamepanel, 620);
    lv_obj_set_height(ui_gamepanel, 371);
    lv_obj_set_x(ui_gamepanel, -18);
    lv_obj_set_y(ui_gamepanel, 18);
    lv_obj_set_align(ui_gamepanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gamepanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_gamepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_gamepanel, lv_color_hex(0x060101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gamepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Easy = lv_button_create(ui_gamepanel);
    lv_obj_set_width(ui_Easy, 114);
    lv_obj_set_height(ui_Easy, 43);
    lv_obj_set_x(ui_Easy, -241);
    lv_obj_set_y(ui_Easy, -59);
    lv_obj_set_align(ui_Easy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Easy, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Easy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Easy, lv_color_hex(0x3C70D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Easy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Easy, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Easy, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Easy);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -3);
    lv_obj_set_y(ui_Label1, 1);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "EASY");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x060000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hard = lv_button_create(ui_gamepanel);
    lv_obj_set_width(ui_Hard, 114);
    lv_obj_set_height(ui_Hard, 43);
    lv_obj_set_x(ui_Hard, -240);
    lv_obj_set_y(ui_Hard, 45);
    lv_obj_set_align(ui_Hard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Hard, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Hard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Hard, lv_color_hex(0x3C70D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Hard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Hard, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Hard, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Hard);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -3);
    lv_obj_set_y(ui_Label4, 1);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "HARD");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x060000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Medium = lv_button_create(ui_gamepanel);
    lv_obj_set_width(ui_Medium, 114);
    lv_obj_set_height(ui_Medium, 43);
    lv_obj_set_x(ui_Medium, -241);
    lv_obj_set_y(ui_Medium, -7);
    lv_obj_set_align(ui_Medium, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Medium, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Medium, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Medium, lv_color_hex(0x3C70D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Medium, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Medium, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Medium, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Medium);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -3);
    lv_obj_set_y(ui_Label5, 1);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "MEDIUM");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x060000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gametitle = lv_label_create(ui_gamepanel);
    lv_obj_set_width(ui_Gametitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Gametitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Gametitle, -240);
    lv_obj_set_y(ui_Gametitle, -128);
    lv_obj_set_align(ui_Gametitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Gametitle, "Catch The \n      Ball");
    lv_obj_set_style_text_color(ui_Gametitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Gametitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Gametitle, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_exitgame = lv_button_create(ui_gamepanel);
    lv_obj_set_width(ui_exitgame, 70);
    lv_obj_set_height(ui_exitgame, 51);
    lv_obj_set_x(ui_exitgame, 261);
    lv_obj_set_y(ui_exitgame, -137);
    lv_obj_set_align(ui_exitgame, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_exitgame, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_exitgame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_exitgame, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_exitgame, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_exitgame, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_exitgame, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arrowimg2 = lv_image_create(ui_exitgame);
    lv_image_set_src(ui_arrowimg2, &ui_img_icn_back_png);
    lv_obj_set_width(ui_arrowimg2, LV_SIZE_CONTENT);   /// 19
    lv_obj_set_height(ui_arrowimg2, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_arrowimg2, -6);
    lv_obj_set_y(ui_arrowimg2, 2);
    lv_obj_set_align(ui_arrowimg2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_arrowimg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Score = lv_label_create(ui_gamepanel);
    lv_obj_set_width(ui_Score, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Score, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Score, -255);
    lv_obj_set_y(ui_Score, 116);
    lv_obj_set_align(ui_Score, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Score, "SCORE : ");
    lv_obj_set_style_text_color(ui_Score, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Score, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Score, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    bucket = lv_obj_create(ui_gamepanel);
    lv_obj_set_size(bucket, 100, 20);
    lv_obj_align(bucket, LV_ALIGN_BOTTOM_MID, 0, -10);
    lv_obj_set_style_bg_color(bucket, lv_color_hex(0x3C70D3), LV_PART_MAIN);
    lv_obj_set_style_radius(bucket, 5, 0);

    lv_obj_add_event_cb(ui_homebtn, ui_event_homebtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rightbtng, ui_event_rightbtng, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_leftbtng, ui_event_leftbtng, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Start, ui_event_Start, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_exitgame, ui_event_exitgame, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Easy, difficulty_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Medium, difficulty_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Hard, difficulty_cb, LV_EVENT_CLICKED, NULL);

    lv_obj_add_event_cb(ui_gamepanel, bucket_move_cb, LV_EVENT_PRESSING, NULL);

}

static void ball_anim_cb(void *var, int32_t v)
{
    lv_obj_t *ball = var;
    lv_obj_set_y(ball, v);

    /* collision check */
    lv_coord_t ball_y = lv_obj_get_y(ball);
    if (ball_y >= lv_obj_get_y(bucket) - 10) {
        lv_coord_t ball_x = lv_obj_get_x(ball);
        lv_coord_t bucket_x = lv_obj_get_x(bucket);
        lv_coord_t bucket_w = lv_obj_get_width(bucket);

        if (ball_x > bucket_x - 20 && ball_x < bucket_x + bucket_w) {
            score++;
            char buf[32];
            sprintf(buf, "SCORE : %d", score);
            lv_label_set_text(ui_Score, buf);
        }
        lv_obj_del(ball);
    }
}

static void spawn_ball(lv_timer_t * timer)
{
    lv_obj_t *ball = lv_obj_create(ui_gamepanel);
    lv_obj_set_size(ball, 20, 20);
    lv_obj_set_style_radius(ball, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_bg_color(ball, lv_color_hex(0xFF0000), LV_PART_MAIN);
    lv_obj_set_x(ball, (rand() % (lv_obj_get_width(ui_gamepanel) - 40)) - (lv_obj_get_width(ui_gamepanel)/2) + 20);
    lv_obj_set_y(ball, -150); // start above panel

    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, ball);
    lv_anim_set_values(&a, -150, lv_obj_get_height(ui_gamepanel));
    lv_anim_set_time(&a, 1100);
    lv_anim_set_exec_cb(&a, ball_anim_cb);
    lv_anim_start(&a);
}

static void difficulty_cb(lv_event_t * e)
{
    lv_obj_t * btn = lv_event_get_target(e);
    const char *txt = lv_label_get_text(lv_obj_get_child(btn, 0));

    if (strcmp(txt, "EASY") == 0) ball_speed = 2000;
    else if (strcmp(txt, "MEDIUM") == 0) ball_speed = 1200;
    else if (strcmp(txt, "HARD") == 0) ball_speed = 700;

    score = 0;
    lv_label_set_text(ui_Score, "SCORE : 0");

    if (ball_timer) lv_timer_del(ball_timer);
    ball_timer = lv_timer_create(spawn_ball, ball_speed, NULL);
}

static void bucket_move_cb(lv_event_t * e)
{
    lv_point_t p;
    lv_indev_get_point(lv_indev_get_act(), &p);

    lv_obj_set_x(bucket, p.x - lv_obj_get_width(bucket)/2 - (lv_obj_get_width(ui_gamepanel)/2));
}

void ui_Graphics_screen_destroy(void)
{
    if(ui_Graphics) lv_obj_del(ui_Graphics);

    // NULL screen variables
    ui_Graphics = NULL;
    ui_graphicslabel = NULL;
    ui_homebtn = NULL;
    ui_home = NULL;
    ui_rightbtng = NULL;
    ui_leftbtng = NULL;
    ui_Start = NULL;
    ui_Label2 = NULL;
    ui_gamepanel = NULL;
    ui_Easy = NULL;
    ui_Label1 = NULL;
    ui_Hard = NULL;
    ui_Label4 = NULL;
    ui_Medium = NULL;
    ui_Label5 = NULL;
    ui_Gametitle = NULL;
    ui_exitgame = NULL;
    ui_arrowimg2 = NULL;
    ui_Score = NULL;

}
