// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Hackathon_squareline

#ifndef UI_VOICE_H
#define UI_VOICE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Voice
extern void ui_Voice_screen_init(void);
extern void ui_Voice_screen_destroy(void);
extern lv_obj_t * ui_Voice;
extern lv_obj_t * ui_voicelabel;
extern void ui_event_homebtn2(lv_event_t * e);
extern lv_obj_t * ui_homebtn2;
extern lv_obj_t * ui_home1;
extern void ui_event_rightbtnv(lv_event_t * e);
extern lv_obj_t * ui_rightbtnv;
extern void ui_event_leftbtnv(lv_event_t * e);
extern lv_obj_t * ui_leftbtnv;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_mic;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

