// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: hui

#ifndef UI_FLOORSCREEN_H
#define UI_FLOORSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_FloorScreen
extern void ui_FloorScreen_screen_init(void);
extern void ui_FloorScreen_screen_destroy(void);
extern lv_obj_t * ui_FloorScreen;
extern lv_obj_t * ui_Panel2;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern void ui_event_Label17(lv_event_t * e);
extern lv_obj_t * ui_Label17;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern void ui_event_Label6(lv_event_t * e);
extern lv_obj_t * ui_Label6;
extern void ui_event_floor2(lv_event_t * e);
extern lv_obj_t * ui_floor2;
extern void ui_event_Label5(lv_event_t * e);
extern lv_obj_t * ui_Label5;
extern void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern void ui_event_Label8(lv_event_t * e);
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label21;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

