// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: hui

#include "../ui.h"

lv_obj_t * ui_FloorScreen = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_floor2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Button10 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label21 = NULL;
// event funtions
void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Room_1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Room_1_screen_init);
    }
}

void ui_event_Label17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Room_1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Room_1_screen_init);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Room_1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Room_1_screen_init);
    }
}

void ui_event_Label6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Room_1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Room_1_screen_init);
    }
}

void ui_event_floor2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Room_1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Room_1_screen_init);
    }
}

void ui_event_Label5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Room_1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Room_1_screen_init);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Room_1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Room_1_screen_init);
    }
}

void ui_event_Label8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Room_1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Room_1_screen_init);
    }
}

// build funtions

void ui_FloorScreen_screen_init(void)
{
    ui_FloorScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_FloorScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FloorScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FloorScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_FloorScreen);
    lv_obj_set_width(ui_Panel2, 829);
    lv_obj_set_height(ui_Panel2, 490);
    lv_obj_set_x(ui_Panel2, 1);
    lv_obj_set_y(ui_Panel2, -6);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Panel2, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_button_create(ui_Panel2);
    lv_obj_set_width(ui_Button8, 217);
    lv_obj_set_height(ui_Button8, 113);
    lv_obj_set_x(ui_Button8, 71);
    lv_obj_set_y(ui_Button8, 115);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "FLOOR 1");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x0B0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_button_create(ui_Panel2);
    lv_obj_set_width(ui_Button9, 217);
    lv_obj_set_height(ui_Button9, 113);
    lv_obj_set_x(ui_Button9, 71);
    lv_obj_set_y(ui_Button9, -38);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "FLOOR 3");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x0B0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_floor2 = lv_button_create(ui_Panel2);
    lv_obj_set_width(ui_floor2, 217);
    lv_obj_set_height(ui_floor2, 116);
    lv_obj_set_x(ui_floor2, -192);
    lv_obj_set_y(ui_floor2, 115);
    lv_obj_set_align(ui_floor2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_floor2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_floor2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_floor2, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_floor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_floor2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "FLOOR 2");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x0B0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_button_create(ui_Panel2);
    lv_obj_set_width(ui_Button10, 217);
    lv_obj_set_height(ui_Button10, 113);
    lv_obj_set_x(ui_Button10, -189);
    lv_obj_set_y(ui_Button10, -39);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0xA8A8A8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "FLOOR 4");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x0B0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_FloorScreen);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -223);
    lv_obj_set_y(ui_Label21, -146);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Select floor\n");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &ui_font_SS48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Label17, ui_event_Label17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label6, ui_event_Label6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label5, ui_event_Label5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_floor2, ui_event_floor2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label8, ui_event_Label8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);

}

void ui_FloorScreen_screen_destroy(void)
{
    if(ui_FloorScreen) lv_obj_del(ui_FloorScreen);

    // NULL screen variables
    ui_FloorScreen = NULL;
    ui_Panel2 = NULL;
    ui_Button8 = NULL;
    ui_Label17 = NULL;
    ui_Button9 = NULL;
    ui_Label6 = NULL;
    ui_floor2 = NULL;
    ui_Label5 = NULL;
    ui_Button10 = NULL;
    ui_Label8 = NULL;
    ui_Label21 = NULL;

}
