// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: hui

#ifndef UI_ROOM_1_H
#define UI_ROOM_1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Room_1
extern void ui_Room_1_screen_init(void);
extern void ui_Room_1_screen_destroy(void);
extern lv_obj_t * ui_Room_1;
extern void ui_event_Panel6(lv_event_t * e);
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_backbutton;
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

