// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: hui

#include "../ui.h"

lv_obj_t * uic_Image1;
lv_obj_t * ui_TEMP = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Spinner2 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Panel14 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Panel17 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Panel18 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Panel16 = NULL;
lv_obj_t * ui_Panel19 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label26 = NULL;
// event funtions
void ui_event_Panel19(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Room_1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Room_1_screen_init);
    }
}

void ui_event_Panel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_label_set_property(ui_Label25, _UI_LABEL_PROPERTY_TEXT, "Close Blinds");
    }
}

// build funtions

void ui_TEMP_screen_init(void)
{
    ui_TEMP = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_TEMP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TEMP, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TEMP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_TEMP);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -208);
    lv_obj_set_y(ui_Label10, -74);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "26°C");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xE2E2E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_Label10, 456, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_TEMP);
    lv_obj_set_width(ui_Panel12, 65);
    lv_obj_set_height(ui_Panel12, 65);
    lv_obj_set_x(ui_Panel12, -223);
    lv_obj_set_y(ui_Panel12, 34);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel12, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Panel12, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0x2873B9), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Panel12);
    lv_image_set_src(ui_Image1, &ui_img_add_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, 1);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel13 = lv_obj_create(ui_TEMP);
    lv_obj_set_width(ui_Panel13, 65);
    lv_obj_set_height(ui_Panel13, 65);
    lv_obj_set_x(ui_Panel13, -123);
    lv_obj_set_y(ui_Panel13, 36);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Panel13, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x2873B9), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_Panel13);
    lv_image_set_src(ui_Image2, &ui_img_remove_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image2, 1);
    lv_obj_set_y(ui_Image2, -2);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner2 = lv_spinner_create(ui_TEMP);
    //lv_spinner_set_anim_params(ui_Spinner2, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 111);
    lv_obj_set_height(ui_Spinner2, 117);
    lv_obj_set_x(ui_Spinner2, 359);
    lv_obj_set_y(ui_Spinner2, -161);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x3939E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner2, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0xE6E6EA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Spinner2);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "0:25");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_SS3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_TEMP);
    lv_obj_set_width(ui_Panel14, 280);
    lv_obj_set_height(ui_Panel14, 70);
    lv_obj_set_x(ui_Panel14, 238);
    lv_obj_set_y(ui_Panel14, -64);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "450 ppm");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_TEMP);
    lv_obj_set_width(ui_Panel17, 280);
    lv_obj_set_height(ui_Panel17, 70);
    lv_obj_set_x(ui_Panel17, 239);
    lv_obj_set_y(ui_Panel17, 12);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 33);
    lv_obj_set_y(ui_Label12, 2);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "98%  Excellent");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_TEMP);
    lv_obj_set_width(ui_Panel18, 280);
    lv_obj_set_height(ui_Panel18, 70);
    lv_obj_set_x(ui_Panel18, 240);
    lv_obj_set_y(ui_Panel18, 89);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "45%");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_TEMP);
    lv_obj_set_width(ui_Panel16, 397);
    lv_obj_set_height(ui_Panel16, 294);
    lv_obj_set_x(ui_Panel16, -164);
    lv_obj_set_y(ui_Panel16, -29);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x434343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_TEMP);
    lv_obj_set_width(ui_Panel19, 284);
    lv_obj_set_height(ui_Panel19, 70);
    lv_obj_set_x(ui_Panel19, 239);
    lv_obj_set_y(ui_Panel19, 171);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0xE84646), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Panel19);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -1);
    lv_obj_set_y(ui_Label18, -1);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "END MEETING");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_TEMP);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 137);
    lv_obj_set_y(ui_Label7, -63);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "CO2");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_TEMP);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 141);
    lv_obj_set_y(ui_Label22, 17);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "SPO2");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_TEMP);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 156);
    lv_obj_set_y(ui_Label23, 92);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Humidity ");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_TEMP);
    lv_obj_set_width(ui_Panel1, 280);
    lv_obj_set_height(ui_Panel1, 70);
    lv_obj_set_x(ui_Panel1, 237);
    lv_obj_set_y(ui_Panel1, -139);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "4 min 20 sec");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_TEMP);
    lv_obj_set_width(ui_Panel3, 200);
    lv_obj_set_height(ui_Panel3, 70);
    lv_obj_set_x(ui_Panel3, -265);
    lv_obj_set_y(ui_Panel3, 163);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Open Blinds");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_TEMP);
    lv_obj_set_width(ui_Panel4, 197);
    lv_obj_set_height(ui_Panel4, 70);
    lv_obj_set_x(ui_Panel4, -64);
    lv_obj_set_y(ui_Panel4, 163);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 128, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Extend");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel19, ui_event_Panel19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel3, ui_event_Panel3, LV_EVENT_ALL, NULL);
    uic_Image1 = ui_Image1;

}

void ui_TEMP_screen_destroy(void)
{
    if(ui_TEMP) lv_obj_del(ui_TEMP);

    // NULL screen variables
    ui_TEMP = NULL;
    ui_Label10 = NULL;
    ui_Panel12 = NULL;
    uic_Image1 = NULL;
    ui_Image1 = NULL;
    ui_Panel13 = NULL;
    ui_Image2 = NULL;
    ui_Spinner2 = NULL;
    ui_Label11 = NULL;
    ui_Panel14 = NULL;
    ui_Label14 = NULL;
    ui_Panel17 = NULL;
    ui_Label12 = NULL;
    ui_Panel18 = NULL;
    ui_Label13 = NULL;
    ui_Panel16 = NULL;
    ui_Panel19 = NULL;
    ui_Label18 = NULL;
    ui_Label7 = NULL;
    ui_Label22 = NULL;
    ui_Label23 = NULL;
    ui_Panel1 = NULL;
    ui_Label24 = NULL;
    ui_Panel3 = NULL;
    ui_Label25 = NULL;
    ui_Panel4 = NULL;
    ui_Label26 = NULL;

}
