// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: hui

#ifndef UI_LOCKSCREEN_H
#define UI_LOCKSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Lockscreen
extern void ui_Lockscreen_screen_init(void);
extern void ui_Lockscreen_screen_destroy(void);
extern lv_obj_t * ui_Lockscreen;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Lockscreen;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

