// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: hui

#ifndef UI_TEMP_H
#define UI_TEMP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TEMP
extern void ui_TEMP_screen_init(void);
extern void ui_TEMP_screen_destroy(void);
extern lv_obj_t * ui_TEMP;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel16;
extern void ui_event_Panel19(lv_event_t * e);
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label24;
extern void ui_event_Panel3(lv_event_t * e);
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label25;
extern void ui_event_Panel4(lv_event_t * e);
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label26;
extern void ui_event_Image1(lv_event_t * e);
extern void ui_event_Image2(lv_event_t * e);
// CUSTOM VARIABLES
extern lv_obj_t * uic_Image1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

