// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: Hackathon_squareline

#ifndef _HACKATHON_SQUARELINE_UI_H
#define _HACKATHON_SQUARELINE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Info.h"
#include "screens/ui_Graphics.h"
#include "screens/ui_Voice.h"
#include "screens/ui_Sensors.h"
#include "screens/ui_Audio.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_icn_home_png);    // assets/icn_home.png
LV_IMG_DECLARE(ui_img_icn_back1_png);    // assets/icn_back1.png
LV_IMG_DECLARE(ui_img_icn_back_png);    // assets/icn_back.png
LV_IMG_DECLARE(ui_img_mic_png);    // assets/mic.png
LV_IMG_DECLARE(ui_img_soundd_png);    // assets/soundd.png
LV_IMG_DECLARE(ui_img_music_png);    // assets/music.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_img_ppause_png);    // assets/ppause.png

// FONTS
LV_FONT_DECLARE(ui_font_SS3);
LV_FONT_DECLARE(ui_font_SS48);
LV_FONT_DECLARE(ui_font_SS52);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
