// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.2.2
// Project name: Hackathon_squareline

#include "ui.h"
#include "app_i2s.h"
#include "audio_playback.h"
#include "playback_config.h"
void play_music(lv_event_t * e)
{
	audio_play();
}

void pause_music(lv_event_t * e)
{
	audio_pause();
}
