// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: hui

#ifndef _HUI_UI_H
#define _HUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_FloorScreen.h"
#include "screens/ui_Lockscreen.h"
#include "screens/ui_Room_1.h"
#include "screens/ui_TEMP.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_icn_back_png);    // assets/icn_back.png
LV_IMG_DECLARE(
    ui_img_add_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/add_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_remove_24dp_e3e3e3_fill0_wght400_grad0_opsz24_png);    // assets/remove_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_SS3);
LV_FONT_DECLARE(ui_font_SS48);
LV_FONT_DECLARE(ui_font_SS52);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
